import type { NextPage } from 'next'
import Head from 'next/head'
import Board from '../containers/Board'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tic Tac Toe (NextJs, React, Typescript)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className='win'>Tic Tac Toe (NextJs, React, Typescript)</h1>
        <Board />
      </main>


    </div>
  )
}

export default Home
